/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package archwayhq/keyring-go/src/go */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* SetOsStore(char* serviceName, char* keyName, char* data);
extern char* GetOsStore(char* serviceName, char* keyName);
extern char** ListOsStore(char* serviceName);
extern char* DeleteOsStore(char* serviceName, char* keyName);

// note: ~/ is root of user dir
//
extern char* SetFileStore(char* fileSaveDir, char* fileName, char* data, char* filePassword);
extern char* GetFileStore(char* fileSaveDir, char* fileName, char* filePassword);

/* Return type for GetFileStoreBytes */
struct GetFileStoreBytes_return {
	void* r0;
	size_t r1;
	char* r2;
};
extern struct GetFileStoreBytes_return GetFileStoreBytes(char* fileSaveDir, char* fileName, char* filePassword);
extern char** ListFileStore(char* fileSaveDir);
extern char* DeleteFileStore(char* fileSaveDir, char* fileName, char* filePassword);

#ifdef __cplusplus
}
#endif
