name: Pre-build binaries

on:
  pull_request:
    branches:
      - main

jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            os: linux
            arch: amd64
          # - runner: ubuntu-latest
          #   os: linux
          #   arch: arm64
          - runner: macos-12
            os: darwin
            arch: amd64
          # - runner: macos-12
          #   os: darwin
          #   arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"
      - run: npm install --ignore-scripts
      - run: npm run build
      - run: npm test
      - name: Commit prebuilt binary
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "build: add binary for ${{ matrix.os }}/${{ matrix.arch }}"
          git push
