name: prebuild-keyring-linux-x64
on:
  pull_request:
    branches:
      - main
jobs:
  build-native-node-module-on-linux:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'          
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'            
      - run: npm install --ignore-scripts
      - run: npm run build:go
      - run: npm run build:node
      - name: Commit prebuilt binary
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add prebuilt binary for linux architecture"
          git push
