name: prebuild-keyring-linux-x64
on:
  pull_request
jobs:
  build-native-node-module-on-linux:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'          
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'            
      - run: npm install --ignore-scripts
      - run: npm run build:go
      - run: npm run build:node
      - run: git add .
      - run: git commit -m "Add prebuilt binary for linux architecture"
      - run: git push"
