name: test-keyring-go
on: [push]
jobs:
  build-native-node-module:    
    strategy:
      matrix:
        os:
          - macos-latest
        compiler:
          - gcc
          - cc
        include:
          - os: windows-latest
            compiler: msvc
    runs-on: ${{ matrix.os }}
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          vcpkg: true
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'          
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'      
      - run: npm install
      - run: npm run build:go:m1
      - run: npm run build:node
      - run: npm run test
      - run: npm run vitest