name: test-linux
on:
  pull_request:
    branches:
      - main
jobs:
  build-native-node-module-on-linux:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'        
      - run: npm install --ignore-scripts
      - run: npm run test
