name: test-keyring-linux-x64
on: [push]
jobs:
  build-native-node-module-on-linux:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'          
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'
      - run: cd ~/
      - run: pwd
      - run: git clone https://github.com/yousefvand/secret-service.git
      - run: sudo apt-get install libglib2.0-dev libdbus-1-dev libdbus-glib-1-dev
      - run: cd secret-service
      - run: make
      - run: sudo make install